# Generated by Django 3.0.1 on 2020-01-26 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_chatterbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='tags',
            field=models.ManyToManyField(related_name='statements', to='django_chatterbot.Tag'),
        ),
        migrations.CreateModel(
            name='StatementTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_chatterbot.Statement')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_chatterbot.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
